#+TITLE: Jobs, results and workflows

* Job
A job  is a collection of related parameters.  
A job object is constructed by instantiating by a subclass
of =Job=. 

* Job Function
A job function takes a job and returns a result, or raises
an =WfExn= wrapped around a result.   A job
function is implemented as a class with three methods
(described later):

 - =is_admissible= :: takes a job and checks if the job is valid
                 for the job function.

 - =is_ready= :: takes a job valid for the function and
                 inquires whether the job is ready to be
                 acted upon

 - =do= :: take a ready job and acts on the job to produce a
           result or a =ResultException=. 


* Result
A result is a collection of related attributes and their
values.  It is obtained as a result of applying a job
function to a job.

A result object has three primary components:

  - job :: the job whose execution gave this result.

  - fun ::  the wf function that operated on the job

It may also have other fields.

* Job Workflow

A Job workflow is a collection of jobs and a sequence of job
functions working on them. 

